name: test-pr

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

on: [pull_request]

jobs:
  test-pr-job:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4
      with:
        github-server-url: https://github.com/dogusyuksel/embedded_docker
        lfs: true

    - name: preparation
      run: |
        df . -h
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df . -h
        mkdir thirdparty
        git clone https://github.com/STMicroelectronics/stm32l4xx_hal_driver.git thirdparty/STM32L4XX_HAL
        git clone https://github.com/modm-io/cmsis-header-stm32.git thirdparty/cmsis-header-stm32
        git clone https://github.com/ARM-software/CMSIS_5.git thirdparty/CMSIS_5
        git clone https://github.com/FreeRTOS/FreeRTOS-Kernel.git thirdparty/FreeRTOS-Kernel
        git clone https://github.com/STMicroelectronics/stm32f1xx_hal_driver.git thirdparty/STM32F103X_HAL
        git clone https://github.com/dogusyuksel/embedded_linting.git thirdparty/linting
        git clone https://github.com/mpaland/printf.git thirdparty/custom_printf
        git clone https://github.com/STMicroelectronics/OpenOCD.git thirdparty/openocd
        cat ./thirdparty/openocd/tcl/board/stm32f103c8_blue_pill.cfg | sed -e "s/set FLASH_SIZE 0x20000/set FLASH_SIZE 0x10000/" > ./thirdparty/openocd/tcl/board/stm32f103c8_custom.cfg
        git clone https://github.com/OpenCyphal/libcanard.git thirdparty/libcanard
        cd thirdparty/libcanard
        git checkout 43de1c4966b8d1e5d57978949d63e697f045b358
        git submodule update --init --recursive
        patch -d . -p1 < ./transport.py.patch && patch -d . -p1 < ./canard_stm32.patch
        cd ..
        git clone https://github.com/DaveGamble/cJSON.git cjson
        cd cjson
        git checkout 87d8f0961a01bf09bef98ff89bae9fdec42181ee
        mkdir build && cd build && cmake .. && make
        cd ../../ && git clone -b kirkstone git://git.yoctoproject.org/poky.git
        git clone https://github.com/dogusyuksel/ti_cc2640r2f_sdk.git ti_cc2640r2f_sdk
        cd .. && ls -al && ls -al thirdparty

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Project Docker
      uses: docker/build-push-action@v5
      with:
        load: true
        tags: |
          ${{ secrets.DOCKER_REPO }}:master
        context: .
        file: Dockerfile
        pull: true
        push: false
        provenance: false

    - name: Hadolint Check
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        failure-threshold: error

    - name: check fs
      run: |
        ./run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd / && ls -al && tree thirdparty cd /workspace && ls -al && tree"

